---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-system
resources:
  - ./externalsecret.yaml
  - ./http-route.yaml

helmCharts:
  - name: kubechecks
    releaseName: kubechecks
    namespace: argo-system
    repo: https://zapier.github.io/kubechecks/
    version: "3.0.0"
    valuesFile: values.yaml
