---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../volsync-system/volsync-replication
resources:
  - ./external-secret.yaml
  - ./configmap.yaml
  - ./rbac.yaml

helmCharts:
  - name: app-template
    releaseName: gitea-runner
    namespace: default
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "4.6.2"
    valuesFile: values.yaml
