---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
helmCharts:
  - name: milvus
    releaseName: milvusdb
    namespace: ai
    repo: https://zilliztech.github.io/milvus-helm/
    version: "5.0.14"
    valuesFile: values.yaml
