---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - name: snapshot-controller
    releaseName: snapshot-controller
    namespace: kube-system
    includeCRDs: true
    repo: oci://ghcr.io/piraeusdatastore/helm-charts
    version: 5.0.1
    valuesFile: values.yaml
