apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./externalsecret.yaml
  - ./http-route.yaml

helmCharts:
  - name: grafana
    releaseName: grafana
    namespace: observability
    repo: oci://ghcr.io/grafana/helm-charts
    version: 10.3.2
    valuesFile: values.yaml
