apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./http-route.yaml
  - ./pvc.yaml
components:
  - ../../volsync-system/volsync-replication
helmCharts:
  - name: nextcloud
    releaseName: nextcloud
    namespace: default
    repo: oci://ghcr.io/nextcloud/helm
    version: "8.9.1"
    valuesFile: values.yaml
