---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./http-route.yaml
components:
  - ../../volsync-system/volsync-replication

helmCharts:
  - name: app-template
    releaseName: audiobookshelf
    namespace: default
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "4.6.0"
    valuesFile: values.yaml
