---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./http-route.yaml
helmCharts:
  - name: app-template
    releaseName: reactive-resume
    namespace: default
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "4.4.0"
    valuesFile: values.yaml
