---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mo-kubeconfigs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mo-kubeconfigs
    template:
      engineVersion: v2
      data:
        talos: "{{ .talos_kubeconfig }}"
        omv: "{{ .omv_kubeconfig }}"
  data:
    - secretKey: talos_kubeconfig
      remoteRef:
        key: talos
        property: mo-kube-config
    - secretKey: omv_kubeconfig
      remoteRef:
        key: omv
        property: mo-kube-config
