---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - rbac.yaml
  - http-route.yaml
generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: app-template
    releaseName: homepage
    namespace: default
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "4.6.2"
    valuesFile: values.yaml
