apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ../../../../../components/observability/kube-prometheus-stack

helmCharts:
  - name: kube-prometheus-stack
    releaseName: kube-prometheus-stack
    namespace: observability
    repo: oci://ghcr.io/prometheus-community/charts
    includeCRDs: true
    version: 79.8.2
    valuesFile: ../../../../../components/observability/kube-prometheus-stack/values.yaml
