---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volsync-system
resources:
  - external-secret.yaml
  - http-route.yaml
  - maintenance-cronjob.yaml

configMapGenerator:
  - name: kopia-repository-configmap
    files:
      - ./config/repository.config

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

helmCharts:
  - name: app-template
    releaseName: kopia
    namespace: volsync-system
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "4.6.2"
    valuesFile: values.yaml
