---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./http-route.yaml
helmCharts:
  - name: loki
    releaseName: loki
    namespace: observability
    repo: oci://ghcr.io/grafana/helm-charts
    version: 6.46.0
    valuesFile: values.yaml
