---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./networking.yaml

helmCharts:
  - name: cilium
    releaseName: cilium
    namespace: kube-system
    repo: oci://ghcr.io/home-operations/charts-mirror
    version: 1.18.5
    valuesFile: values.yaml
