---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../components/kube-system/cilium

helmCharts:
  - name: cilium
    releaseName: cilium
    namespace: kube-system
    repo: https://helm.cilium.io
    version: 1.18.4
    valuesFile: values.yaml
