apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-system
resources:
  - externalsecret.yaml
helmCharts:
  - name: argocd-image-updater
    releaseName: argocd-image-updater
    namespace: argo-system
    repo: https://argoproj.github.io/argo-helm
    version: "1.1.1"
    valuesFile: values.yaml
