config:
  registries:
    - name: gitea
      prefix: gitea.omv.${CLUSTER_DOMAIN}
      api_url: https://gitea.omv.${CLUSTER_DOMAIN}
      credentials: pullsecret:argo-system/gitea-registry-secret
      insecure: false
  argocd:
    serverAddress: argocd-server.argo-system.svc.cluster.local
    insecure: true
    plaintext: true
metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    additionalLabels:
      release: kube-prometheus-stack
