---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ./issuers

helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    namespace: cert-manager
    repo: oci://quay.io/jetstack/charts
    version: v1.19.3
    valuesFile: values.yaml
