apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./externalsecret.yaml
  - ./http-route.yaml
helmCharts:
  - name: app-template
    releaseName: prowlarr
    namespace: downloads
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "4.5.0"
    valuesFile: values.yaml
