---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./http-route.yaml

helmCharts:
  - name: airflow
    releaseName: airflow
    namespace: default
    repo: https://airflow.apache.org
    version: "1.18.0"
    valuesFile: values.yaml
