---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

helmCharts:
  - name: postgresql
    releaseName: postgres
    namespace: storage
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 18.2.0
    valuesFile: values.yaml
