---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../volsync-system/volsync-replication
resources:
  - ./external-secret.yaml
  - ./http-route.yaml

configMapGenerator:
  - files:
      - config.yml=./resources/config.yaml
    name: romm-configmap

helmCharts:
  - name: app-template
    releaseName: romm
    namespace: default
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "4.5.0"
    valuesFile: values.yaml
