apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./http-route.yaml
components:
  - ../../volsync-system/volsync-replication
helmCharts:
  - name: app-template
    releaseName: node-red
    namespace: default
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "4.6.2"
    valuesFile: values.yaml
