---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./http-route.yaml
helmCharts:
  - name: authentik
    releaseName: authentik
    namespace: default
    repo: oci://ghcr.io/goauthentik/helm-charts
    version: "2025.12.4"
    valuesFile: values.yaml
