---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./external-secret.yaml
  - ./http-route.yaml
  - ./rbac.yaml
helmCharts:
  - name: app-template
    releaseName: kite
    namespace: default
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "4.6.2"
    valuesFile: values.yaml
