apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - external-secrets.yaml
helmCharts:
  - name: reflector
    releaseName: reflector
    namespace: kube-system
    repo: https://emberstack.github.io/helm-charts
    version: "10.0.11"
