---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

helmCharts:
  - name: postgresql
    releaseName: postgres
    namespace: default
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 18.2.3
    valuesFile: values.yaml
