---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

helmCharts:
  - name: velero
    releaseName: velero
    namespace: storage
    repo: https://vmware-tanzu.github.io/helm-charts/
    version: 8.7.2
    valuesFile: values.yaml

patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/dnsPolicy
        value: "None"
      - op: replace
        path: /spec/template/spec/dnsConfig
        value:
          nameservers:
            - 10.30.0.1
    target:
      kind: DaemonSet
      name: node-agent
