---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - schedule-pvc-backup.yaml
# Restore templates (uncomment when needed):
#   - restore-pvc-by-name.yaml
#   - restore-pvc-namespace.yaml
helmCharts:
  - name: velero
    releaseName: velero
    namespace: storage
    repo: https://vmware-tanzu.github.io/helm-charts/
    version: v8.3.0
    valuesFile: values.yaml
