---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

helmCharts:
  - name: velero
    releaseName: velero
    namespace: storage
    repo: https://vmware-tanzu.github.io/helm-charts/
    version: v8.3.0
    valuesFile: values.yaml
