---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

helmCharts:
  - name: velero
    releaseName: velero
    namespace: velero
    repo: https://vmware-tanzu.github.io/helm-charts/
    version: 11.3.1
    valuesFile: values.yaml
