---
# Cluster-specific deployment patch for Kopia
# Adds NFS volume for repository storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopia
spec:
  template:
    spec:
      volumes:
        - name: repository
          nfs:
            server: omv-baymx.a113.internal
            path: "/storage0/VolsyncKopia"
      initContainers:
        - name: copy-config
          volumeMounts:
            - name: repository
              mountPath: /repository
      containers:
        - name: app
          volumeMounts:
            - name: repository
              mountPath: /repository
