---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../components/volsync-system/kopia

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: kopia
  - path: cronjob-patch.yaml
    target:
      kind: CronJob
      name: kopia-maintenance
