---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./externalsecret.yaml
components:
  - ../../volsync-system/volsync-replication
configMapGenerator:
  - name: recyclarr-configmap
    files:
      - recyclarr.yml=./config/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

helmCharts:
  - name: app-template
    releaseName: recyclarr
    namespace: default
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: "4.6.0"
    valuesFile: values.yaml
